config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("transit_odp.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        "publish/",
        include("transit_odp.publish.urls", namespace="publish"),
    ),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

transit_odp/publish/urls.py
from django.conf.urls import url

from transit_odp.publish.views import FeedUploadWizard

app_name = 'publish'
urlpatterns = [
    url(r'', FeedUploadWizard.as_view(), name='new'),
]

transit_odp/users/urls.py
from django.urls import path

from transit_odp.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

transit_odp/publish/models.py
from django.db import models


class Feed(models.Model):
    name = models.CharField(help_text='The name of the feed', max_length=255)
    description = models.TextField(blank=True, help_text='A description of the feed')
    dataset = models.FileField(null=True, blank=True, help_text='The dataset to upload')
    remote = models.URLField(blank=True, help_text='A url to the package')

transit_odp/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

transit_odp/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

transit_odp/publish/views.py
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render
from formtools.wizard.views import SessionWizardView

from transit_odp.publish.form import FeedNameForm, FeedDescriptionForm, FeedUploadForm
from transit_odp.publish.models import Feed


class FeedUploadWizard(SessionWizardView):
    file_storage = FileSystemStorage(location=settings.MEDIA_ROOT)
    form_list = [FeedNameForm, FeedDescriptionForm, FeedUploadForm]
    template_name = 'feed_form.html'

    def done(self, form_list, **kwargs):

        all_data = self.get_all_cleaned_data()

        feed = Feed(**all_data)
        feed.save()

        return render(self.request, 'done.html', {
            'form_data': all_data,
        })

transit_odp/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

transit_odp/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

transit_odp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="govuk-template ">

<head>
  <meta charset="utf-8"/>
  <title>GOV.UK - The best place to find government services and information</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#0b0c0c"/>

  <link rel="shortcut icon" sizes="16x16 32x32 48x48" href="{% static 'images/favicon.ico' %}" type="image/x-icon"/>
  <link rel="mask-icon" href="{% static 'images/govuk-mask-icon.svg' %}" color="#0b0c0c">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/govuk-apple-touch-icon-180x180.png' %}">
  <link rel="apple-touch-icon" sizes="167x167" href="{% static 'images/govuk-apple-touch-icon-167x167.png' %}">
  <link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/govuk-apple-touch-icon-152x152.png' %}">
  <link rel="apple-touch-icon" href="{% static 'images/govuk-apple-touch-icon.png' %}">

  {% block styles %}
    <link href="{% static 'css/govuk-frontend-2.2.0.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/shared.css' %}" rel="stylesheet">
  {% endblock %}

  {% block head %}
  {% endblock %}

  <meta property="og:image" content="{% static 'images/govuk-opengraph-image.png' %}">
</head>

<body class="govuk-template__body ">
<script>
  document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');
</script>

<a href="#main-content" class="govuk-skip-link">Skip to main content</a>

{% block page %}{% endblock %}

{% block scripts %}
  <script src="{% static 'js/govuk-frontend-2.2.0.min.js' %}"></script>
  <script src="{% static 'js/shared.js' %}"></script>
{% endblock %}

</body>

</html>

transit_odp/templates/done.html
{% extends 'page.html' %}


{% block content %}
  {{ form_data }}
{% endblock %}

transit_odp/templates/feed_form.html
{% extends 'page.html' %}

{% load i18n %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ wizard.form.media }}
    {{ wizard.management_form }}
    {% if wizard.form.forms %}
      {{ wizard.form.management_form }}
      {% for form in wizard.form.forms %}
        {{ form.as_p }}
      {% endfor %}
    {% else %}
      {{ wizard.form.as_p }}
    {% endif %}

    {% if wizard.steps.prev %}
      <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% trans "first step" %}</button>
      <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% trans "prev step" %}</button>
    {% endif %}
    <input type="submit" name="submit" value="{% trans "submit" %}"/>
  </form>
{% endblock %}

transit_odp/templates/footer.html
{% load static %}

<footer class="govuk-footer " role="contentinfo">
  <div class="govuk-width-container ">
    <div class="govuk-footer__meta">
      <div class="govuk-footer__meta-item govuk-footer__meta-item--grow">

        <svg role="presentation" focusable="false" class="govuk-footer__licence-logo" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 483.2 195.7" height="17" width="41">
          <path fill="currentColor" d="M421.5 142.8V.1l-50.7 32.3v161.1h112.4v-50.7zm-122.3-9.6A47.12 47.12 0 0 1 221 97.8c0-26 21.1-47.1 47.1-47.1 16.7 0 31.4 8.7 39.7 21.8l42.7-27.2A97.63 97.63 0 0 0 268.1 0c-36.5 0-68.3 20.1-85.1 49.7A98 98 0 0 0 97.8 0C43.9 0 0 43.9 0 97.8s43.9 97.8 97.8 97.8c36.5 0 68.3-20.1 85.1-49.7a97.76 97.76 0 0 0 149.6 25.4l19.4 22.2h3v-87.8h-80l24.3 27.5zM97.8 145c-26 0-47.1-21.1-47.1-47.1s21.1-47.1 47.1-47.1 47.2 21 47.2 47S123.8 145 97.8 145"
          />
        </svg>
        <span class="govuk-footer__licence-description">
          All content is available under the
          <a class="govuk-footer__link" href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence v3.0</a>, except where otherwise stated
        </span>
      </div>
      <div class="govuk-footer__meta-item">
        <a class="govuk-footer__link govuk-footer__copyright-logo" href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/">© Crown copyright</a>
      </div>
    </div>
  </div>
</footer>

transit_odp/templates/page.html
{% extends "base.html" %}

{% load i18n %}

{% block page %}
  {% block header %}
    {% include "header.html" %}
  {% endblock %}

  <div class="govuk-width-container">
    <div class="govuk-phase-banner">
      <p class="govuk-phase-banner__content"><strong class="govuk-tag govuk-phase-banner__content__tag ">
        alpha
      </strong>
        <span class="govuk-phase-banner__text">
              This is a new service – your
              <a class="govuk-link" href="#">feedback</a> will help us to improve it.
            </span>
      </p>
    </div>

    {% block breadcrumb %}
      <div class="govuk-breadcrumbs">
        <ol class="govuk-breadcrumbs__list">
          <li class="govuk-breadcrumbs__list-item">
            <a class="govuk-breadcrumbs__link" href="/">{% trans 'Home' %}</a>
          </li>
          {% block breadcrumb_content %}{% endblock %}
        </ol>
      </div>
    {% endblock %}

    <main class="govuk-main-wrapper app-main-class" id="main-content" role="main">
      {% block content %}
      {% endblock %}
    </main>
  </div>

  {% block footer %}
    {% include "footer.html" %}
  {% endblock %}
{% endblock %}

transit_odp/templates/pages/about.html
{% extends "page.html" %}

transit_odp/templates/pages/home.html
{% extends 'page.html' %}

{% block content %}

    <h1>Home Page</h1>

{% endblock %}

transit_odp/templates/users/user_detail.html
{% extends "page.html" %}
{% load static %}

{% block content %}

  {% block title %}User: {{ object.username }}{% endblock %}

  <div class="container">

    <div class="row">
      <div class="col-sm-12">

        <h2>{{ object.username }}</h2>
        {% if object.name %}
          <p>{{ object.name }}</p>
        {% endif %}
      </div>
    </div>

    {% if object == request.user %}
      <!-- Action buttons -->
      <div class="row">

        <div class="col-sm-12">
          <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
          <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
          <!-- Your Stuff: Custom user template urls -->
        </div>

      </div>
      <!-- End Action buttons -->
    {% endif %}


  </div>

{% endblock %}

transit_odp/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

transit_odp/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}